import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {HeaderComponent} from "@/modules/header";
import Head from "next/head";
import {JoinWaitlist} from "@/modules/joinMovement";
import {Footer} from "@/modules/footer";
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
    subsets: ['latin'],
    // weight: '',
    variable: '--font-Montserat',
});

const geistSans = Geist({
    variable: "--font-Montserat",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-Montserat",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <Head>
            <meta name="description" content="Generated by create next app"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
            <link
                href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
                rel="stylesheet"
            />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
            <link
                href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
                rel="stylesheet"/>
        </Head>

        <body
            className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
        >
        <HeaderComponent/>
        {children}
        <JoinWaitlist/>
        <Footer/>
        </body>
        </html>
    );
}
